version: "3"
services:
  app:
    build: .
    container_name: messaging_system
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      # - DB_USER=postgres
      # - DB_PASSWORD=000000
      # - DB_HOST=db
      # - DB_DATABASE=messaging_db
      # - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - app-network

  #postgres service
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "000000"
      POSTGRES_DB: "messaging_db"
    # volumes:
    # - postgres-data:/var/lib/postgresql/data
    # - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network

  #redis service
  redis:
    image: redis:latest
    container_name: redis-server
    networks:
      - app-network

#volumes:
#postgres-data:

networks:
  app-network:
    driver: bridge
