version: "3"
services:
  app:
    build: .
    container_name: messaging_system
    env_file: ./.env.dev
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db
      - redis
    networks:
      app-network:
        #name: app-network
        #attachable: true

  #postgres service
  db:
    image: postgres:latest
    container_name: postgres-db
    env_file: ./.env.dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    # volumes:
    # - postgres-data:/var/lib/postgresql/data
    # - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network

  #redis service
  redis:
    image: redis:latest
    container_name: redis-server
    env_file: ./.env.dev
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - app-network

#volumes:
#postgres-data:

networks:
  app-network:
    driver: bridge
